INFO: 2020-03-17 21:31:43 
-------- START EXPERIMENT --------
INFO: 2020-03-17 21:31:43 
- PROPERTIES -
INFO: 2020-03-17 21:31:43 
{'data': 'elliptic',
 'data_config_file': 'configuration/data/data_config.yaml',
 'elliptic_args': {'encode_classes': True,
                   'feat_sets': ['LF'],
                   'inc_unknown': False,
                   'indexed_by_time': True,
                   'train_size': 0.7},
 'evaluation_metrics': ['precision', 'recall', 'f1', 'f1_micro', 'confusion'],
 'log_path': 'logs/',
 'models': ['xg_boost'],
 'save_log': True,
 'xg_boost_args': {'arguments': {'n_jobs': 4, 'verbosity': 1},
                   'extract_results': {'evaluation_metrics': ['precision',
                                                              'recall',
                                                              'f1',
                                                              'f1_micro',
                                                              'confusion',
                                                              'feature_importance'],
                                       'result_type': 'deterministic'},
                   'persist_props': {'method': 'save',
                                     'save_path': 'saved_models/experiment_1/tuned'}}}
ERROR: 2020-03-17 21:31:43 
(<class 'AttributeError'>, AttributeError("'Namespace' object has no attribute 'extract_results'"), <traceback object at 0x7f82401c2eb0>)
Traceback (most recent call last):
  File "experiment.py", line 198, in <module>
    print(args.extract_results)
AttributeError: 'Namespace' object has no attribute 'extract_results'
